# Generated by Django 3.0.6 on 2020-05-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200526_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='participants',
        ),
    ]
