# Generated by Django 3.0.6 on 2020-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200529_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechannels',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
