export const LOGIN_FORM_SUBMIT='LOGIN_FORM_SUBMIT';
export const SIGNUP_FORM_SUBMIT='SIGNUP_FORM_SUBMIT';
export const FETCH_USER='FETCH_USER';
export const FETCH_USERS='FETCH_USERS';
export const FETCH_CHANNELS='FETCH_CHANNELS';
export const CHANGE_USERNAME='CHANGE_USERNAME';
export const CHANGE_PASSWORD='CHANGE_PASSWORD';